在`/var/log/storage/PEON/PEON.log`中。
有日志：
```
2021-10-18 14:13:09.030915-[ERROR]-[PEON]-[pid:3139330][tid:3146589][snap_utils.py][is_omap_key_exist][line:1554]:
  Cannot find object snap_hardlink in metadata pool.
```
在ceph-dse.engine.65539.9.log中有对应错误：
```
// 创建
2021-10-18 14:13:07.679181 // op tid: 1
